[2019-07-05 19:31:54,724][vert.x-eventloop-thread-0][INFO][com.rome.uaa.MainVerticle:73] 初始化配置成功
[2019-07-05 19:32:00,070][vert.x-eventloop-thread-0][INFO][org.hibernate.validator.internal.util.Version:21] HV000001: Hibernate Validator 6.0.16.Final
[2019-07-05 19:32:00,451][vert.x-eventloop-thread-1][ERROR][com.github.mauricio.async.db.postgresql.PostgreSQLConnection:172] Error with message -> ErrorMessage(fields=Map(Detail -> Key (user_phone)=(4223334142838386) already exists., s -> public, n -> basic_account_user_phone_idx, t -> basic_account, Line -> 535, File -> nbtinsert.c, SQLSTATE -> 23505, Routine -> _bt_check_unique, V -> ERROR, Message -> duplicate key value violates unique constraint "basic_account_user_phone_idx", Severity -> ERROR))
[2019-07-05 19:32:00,452][vert.x-eventloop-thread-1][ERROR][com.github.mauricio.async.db.postgresql.PostgreSQLConnection:152] Error on connection
com.github.mauricio.async.db.postgresql.exceptions.GenericDatabaseException: ErrorMessage(fields=Map(Detail -> Key (user_phone)=(4223334142838386) already exists., s -> public, n -> basic_account_user_phone_idx, t -> basic_account, Line -> 535, File -> nbtinsert.c, SQLSTATE -> 23505, Routine -> _bt_check_unique, V -> ERROR, Message -> duplicate key value violates unique constraint "basic_account_user_phone_idx", Severity -> ERROR))
	at com.github.mauricio.async.db.postgresql.PostgreSQLConnection.onError(PostgreSQLConnection.scala:175) [postgresql-async_2.12-0.2.21.jar:0.2.21]
	at com.github.mauricio.async.db.postgresql.codec.PostgreSQLConnectionHandler.channelRead0(PostgreSQLConnectionHandler.scala:206) [postgresql-async_2.12-0.2.21.jar:0.2.21]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) [netty-codec-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [netty-codec-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426) [netty-codec-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) [netty-codec-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) [netty-common-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.30.Final.jar:4.1.30.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
[2019-07-05 19:32:00,456][vert.x-eventloop-thread-1][ERROR][com.github.mauricio.async.db.postgresql.PostgreSQLConnection:310] Setting error on future Future(<not completed>)
[2019-07-05 19:32:00,463][vert.x-eventloop-thread-0][INFO][com.rome.uaa.service.UaaServiceImpl:57] 2 exceptions occurred. 
[2019-07-05 19:32:26,147][vert.x-eventloop-thread-0][INFO][com.rome.uaa.MainVerticle:73] 初始化配置成功
[2019-07-05 19:32:29,799][vert.x-eventloop-thread-0][INFO][org.hibernate.validator.internal.util.Version:21] HV000001: Hibernate Validator 6.0.16.Final
[2019-07-05 19:32:30,162][vert.x-eventloop-thread-1][ERROR][com.github.mauricio.async.db.postgresql.PostgreSQLConnection:172] Error with message -> ErrorMessage(fields=Map(Detail -> Key (user_phone)=(4223334142838386) already exists., s -> public, n -> basic_account_user_phone_idx, t -> basic_account, Line -> 535, File -> nbtinsert.c, SQLSTATE -> 23505, Routine -> _bt_check_unique, V -> ERROR, Message -> duplicate key value violates unique constraint "basic_account_user_phone_idx", Severity -> ERROR))
[2019-07-05 19:32:30,163][vert.x-eventloop-thread-1][ERROR][com.github.mauricio.async.db.postgresql.PostgreSQLConnection:152] Error on connection
com.github.mauricio.async.db.postgresql.exceptions.GenericDatabaseException: ErrorMessage(fields=Map(Detail -> Key (user_phone)=(4223334142838386) already exists., s -> public, n -> basic_account_user_phone_idx, t -> basic_account, Line -> 535, File -> nbtinsert.c, SQLSTATE -> 23505, Routine -> _bt_check_unique, V -> ERROR, Message -> duplicate key value violates unique constraint "basic_account_user_phone_idx", Severity -> ERROR))
	at com.github.mauricio.async.db.postgresql.PostgreSQLConnection.onError(PostgreSQLConnection.scala:175) [postgresql-async_2.12-0.2.21.jar:0.2.21]
	at com.github.mauricio.async.db.postgresql.codec.PostgreSQLConnectionHandler.channelRead0(PostgreSQLConnectionHandler.scala:206) [postgresql-async_2.12-0.2.21.jar:0.2.21]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) [netty-codec-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [netty-codec-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426) [netty-codec-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) [netty-codec-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) [netty-common-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.30.Final.jar:4.1.30.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
[2019-07-05 19:32:30,167][vert.x-eventloop-thread-1][ERROR][com.github.mauricio.async.db.postgresql.PostgreSQLConnection:310] Setting error on future Future(<not completed>)
[2019-07-05 19:32:30,172][vert.x-eventloop-thread-0][INFO][com.rome.uaa.service.UaaServiceImpl:57] 2 exceptions occurred. 
[2019-07-05 19:32:48,531][vert.x-eventloop-thread-0][INFO][com.rome.uaa.MainVerticle:73] 初始化配置成功
[2019-07-05 19:32:51,317][vert.x-eventloop-thread-0][INFO][org.hibernate.validator.internal.util.Version:21] HV000001: Hibernate Validator 6.0.16.Final
[2019-07-05 19:32:51,730][vert.x-eventloop-thread-1][ERROR][com.github.mauricio.async.db.postgresql.PostgreSQLConnection:172] Error with message -> ErrorMessage(fields=Map(Detail -> Key (user_phone)=(4223334142838386) already exists., s -> public, n -> basic_account_user_phone_idx, t -> basic_account, Line -> 535, File -> nbtinsert.c, SQLSTATE -> 23505, Routine -> _bt_check_unique, V -> ERROR, Message -> duplicate key value violates unique constraint "basic_account_user_phone_idx", Severity -> ERROR))
[2019-07-05 19:32:51,731][vert.x-eventloop-thread-1][ERROR][com.github.mauricio.async.db.postgresql.PostgreSQLConnection:152] Error on connection
com.github.mauricio.async.db.postgresql.exceptions.GenericDatabaseException: ErrorMessage(fields=Map(Detail -> Key (user_phone)=(4223334142838386) already exists., s -> public, n -> basic_account_user_phone_idx, t -> basic_account, Line -> 535, File -> nbtinsert.c, SQLSTATE -> 23505, Routine -> _bt_check_unique, V -> ERROR, Message -> duplicate key value violates unique constraint "basic_account_user_phone_idx", Severity -> ERROR))
	at com.github.mauricio.async.db.postgresql.PostgreSQLConnection.onError(PostgreSQLConnection.scala:175) [postgresql-async_2.12-0.2.21.jar:0.2.21]
	at com.github.mauricio.async.db.postgresql.codec.PostgreSQLConnectionHandler.channelRead0(PostgreSQLConnectionHandler.scala:206) [postgresql-async_2.12-0.2.21.jar:0.2.21]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) [netty-codec-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [netty-codec-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426) [netty-codec-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) [netty-codec-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) [netty-common-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.30.Final.jar:4.1.30.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
[2019-07-05 19:32:51,735][vert.x-eventloop-thread-1][ERROR][com.github.mauricio.async.db.postgresql.PostgreSQLConnection:310] Setting error on future Future(<not completed>)
[2019-07-05 19:32:51,741][vert.x-eventloop-thread-0][INFO][com.rome.uaa.service.UaaServiceImpl:57] 2 exceptions occurred. 
[2019-07-05 19:33:41,347][vert.x-eventloop-thread-0][INFO][com.rome.uaa.MainVerticle:73] 初始化配置成功
[2019-07-05 19:33:45,335][vert.x-eventloop-thread-0][INFO][org.hibernate.validator.internal.util.Version:21] HV000001: Hibernate Validator 6.0.16.Final
[2019-07-05 19:33:45,726][vert.x-eventloop-thread-1][ERROR][com.github.mauricio.async.db.postgresql.PostgreSQLConnection:172] Error with message -> ErrorMessage(fields=Map(Detail -> Key (user_phone)=(4223334142838386) already exists., s -> public, n -> basic_account_user_phone_idx, t -> basic_account, Line -> 535, File -> nbtinsert.c, SQLSTATE -> 23505, Routine -> _bt_check_unique, V -> ERROR, Message -> duplicate key value violates unique constraint "basic_account_user_phone_idx", Severity -> ERROR))
[2019-07-05 19:33:45,727][vert.x-eventloop-thread-1][ERROR][com.github.mauricio.async.db.postgresql.PostgreSQLConnection:152] Error on connection
com.github.mauricio.async.db.postgresql.exceptions.GenericDatabaseException: ErrorMessage(fields=Map(Detail -> Key (user_phone)=(4223334142838386) already exists., s -> public, n -> basic_account_user_phone_idx, t -> basic_account, Line -> 535, File -> nbtinsert.c, SQLSTATE -> 23505, Routine -> _bt_check_unique, V -> ERROR, Message -> duplicate key value violates unique constraint "basic_account_user_phone_idx", Severity -> ERROR))
	at com.github.mauricio.async.db.postgresql.PostgreSQLConnection.onError(PostgreSQLConnection.scala:175) [postgresql-async_2.12-0.2.21.jar:0.2.21]
	at com.github.mauricio.async.db.postgresql.codec.PostgreSQLConnectionHandler.channelRead0(PostgreSQLConnectionHandler.scala:206) [postgresql-async_2.12-0.2.21.jar:0.2.21]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) [netty-codec-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [netty-codec-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426) [netty-codec-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) [netty-codec-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) [netty-common-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.30.Final.jar:4.1.30.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
[2019-07-05 19:33:45,731][vert.x-eventloop-thread-1][ERROR][com.github.mauricio.async.db.postgresql.PostgreSQLConnection:310] Setting error on future Future(<not completed>)
[2019-07-05 19:33:45,737][vert.x-eventloop-thread-0][INFO][com.rome.uaa.service.UaaServiceImpl:57] 2 exceptions occurred. 
[2019-07-05 19:34:06,714][vert.x-eventloop-thread-0][INFO][com.rome.uaa.MainVerticle:74] 初始化配置成功
[2019-07-05 19:34:10,706][vert.x-eventloop-thread-0][INFO][org.hibernate.validator.internal.util.Version:21] HV000001: Hibernate Validator 6.0.16.Final
[2019-07-05 19:34:11,095][vert.x-eventloop-thread-1][ERROR][com.github.mauricio.async.db.postgresql.PostgreSQLConnection:172] Error with message -> ErrorMessage(fields=Map(Detail -> Key (user_phone)=(4223334142838386) already exists., s -> public, n -> basic_account_user_phone_idx, t -> basic_account, Line -> 535, File -> nbtinsert.c, SQLSTATE -> 23505, Routine -> _bt_check_unique, V -> ERROR, Message -> duplicate key value violates unique constraint "basic_account_user_phone_idx", Severity -> ERROR))
[2019-07-05 19:34:11,095][vert.x-eventloop-thread-1][ERROR][com.github.mauricio.async.db.postgresql.PostgreSQLConnection:152] Error on connection
com.github.mauricio.async.db.postgresql.exceptions.GenericDatabaseException: ErrorMessage(fields=Map(Detail -> Key (user_phone)=(4223334142838386) already exists., s -> public, n -> basic_account_user_phone_idx, t -> basic_account, Line -> 535, File -> nbtinsert.c, SQLSTATE -> 23505, Routine -> _bt_check_unique, V -> ERROR, Message -> duplicate key value violates unique constraint "basic_account_user_phone_idx", Severity -> ERROR))
	at com.github.mauricio.async.db.postgresql.PostgreSQLConnection.onError(PostgreSQLConnection.scala:175) [postgresql-async_2.12-0.2.21.jar:0.2.21]
	at com.github.mauricio.async.db.postgresql.codec.PostgreSQLConnectionHandler.channelRead0(PostgreSQLConnectionHandler.scala:206) [postgresql-async_2.12-0.2.21.jar:0.2.21]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) [netty-codec-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) [netty-codec-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) [netty-common-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.30.Final.jar:4.1.30.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
[2019-07-05 19:34:11,099][vert.x-eventloop-thread-1][ERROR][com.github.mauricio.async.db.postgresql.PostgreSQLConnection:310] Setting error on future Future(<not completed>)
[2019-07-05 19:34:11,104][vert.x-eventloop-thread-0][INFO][com.rome.uaa.service.UaaServiceImpl:57] 2 exceptions occurred. 
[2019-07-05 19:34:51,586][vert.x-eventloop-thread-1][ERROR][com.github.mauricio.async.db.postgresql.PostgreSQLConnection:172] Error with message -> ErrorMessage(fields=Map(Detail -> Key (user_phone)=(42233341421838386) already exists., s -> public, n -> basic_account_user_phone_idx, t -> basic_account, Line -> 535, File -> nbtinsert.c, SQLSTATE -> 23505, Routine -> _bt_check_unique, V -> ERROR, Message -> duplicate key value violates unique constraint "basic_account_user_phone_idx", Severity -> ERROR))
[2019-07-05 19:34:51,587][vert.x-eventloop-thread-1][ERROR][com.github.mauricio.async.db.postgresql.PostgreSQLConnection:152] Error on connection
com.github.mauricio.async.db.postgresql.exceptions.GenericDatabaseException: ErrorMessage(fields=Map(Detail -> Key (user_phone)=(42233341421838386) already exists., s -> public, n -> basic_account_user_phone_idx, t -> basic_account, Line -> 535, File -> nbtinsert.c, SQLSTATE -> 23505, Routine -> _bt_check_unique, V -> ERROR, Message -> duplicate key value violates unique constraint "basic_account_user_phone_idx", Severity -> ERROR))
	at com.github.mauricio.async.db.postgresql.PostgreSQLConnection.onError(PostgreSQLConnection.scala:175) [postgresql-async_2.12-0.2.21.jar:0.2.21]
	at com.github.mauricio.async.db.postgresql.codec.PostgreSQLConnectionHandler.channelRead0(PostgreSQLConnectionHandler.scala:206) [postgresql-async_2.12-0.2.21.jar:0.2.21]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) [netty-codec-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) [netty-codec-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) [netty-common-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.30.Final.jar:4.1.30.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
[2019-07-05 19:34:51,588][vert.x-eventloop-thread-1][ERROR][com.github.mauricio.async.db.postgresql.PostgreSQLConnection:310] Setting error on future Future(<not completed>)
[2019-07-05 19:34:51,590][vert.x-eventloop-thread-0][INFO][com.rome.uaa.service.UaaServiceImpl:57] 2 exceptions occurred. 
[2019-07-05 19:36:24,400][vert.x-eventloop-thread-1][ERROR][com.github.mauricio.async.db.postgresql.PostgreSQLConnection:172] Error with message -> ErrorMessage(fields=Map(Detail -> Key (user_phone)=(41661664466) already exists., s -> public, n -> basic_account_user_phone_idx, t -> basic_account, Line -> 535, File -> nbtinsert.c, SQLSTATE -> 23505, Routine -> _bt_check_unique, V -> ERROR, Message -> duplicate key value violates unique constraint "basic_account_user_phone_idx", Severity -> ERROR))
[2019-07-05 19:36:24,401][vert.x-eventloop-thread-1][ERROR][com.github.mauricio.async.db.postgresql.PostgreSQLConnection:152] Error on connection
com.github.mauricio.async.db.postgresql.exceptions.GenericDatabaseException: ErrorMessage(fields=Map(Detail -> Key (user_phone)=(41661664466) already exists., s -> public, n -> basic_account_user_phone_idx, t -> basic_account, Line -> 535, File -> nbtinsert.c, SQLSTATE -> 23505, Routine -> _bt_check_unique, V -> ERROR, Message -> duplicate key value violates unique constraint "basic_account_user_phone_idx", Severity -> ERROR))
	at com.github.mauricio.async.db.postgresql.PostgreSQLConnection.onError(PostgreSQLConnection.scala:175) [postgresql-async_2.12-0.2.21.jar:0.2.21]
	at com.github.mauricio.async.db.postgresql.codec.PostgreSQLConnectionHandler.channelRead0(PostgreSQLConnectionHandler.scala:206) [postgresql-async_2.12-0.2.21.jar:0.2.21]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) [netty-codec-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [netty-codec-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426) [netty-codec-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) [netty-codec-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) [netty-common-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.30.Final.jar:4.1.30.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
[2019-07-05 19:36:24,402][vert.x-eventloop-thread-1][ERROR][com.github.mauricio.async.db.postgresql.PostgreSQLConnection:310] Setting error on future Future(<not completed>)
[2019-07-05 19:36:24,403][vert.x-eventloop-thread-0][INFO][com.rome.uaa.service.UaaServiceImpl:57] 2 exceptions occurred. 
[2019-07-05 19:36:32,738][vert.x-eventloop-thread-1][ERROR][com.github.mauricio.async.db.postgresql.PostgreSQLConnection:172] Error with message -> ErrorMessage(fields=Map(Detail -> Key (user_phone)=(41661664466) already exists., s -> public, n -> basic_account_user_phone_idx, t -> basic_account, Line -> 535, File -> nbtinsert.c, SQLSTATE -> 23505, Routine -> _bt_check_unique, V -> ERROR, Message -> duplicate key value violates unique constraint "basic_account_user_phone_idx", Severity -> ERROR))
[2019-07-05 19:36:32,738][vert.x-eventloop-thread-1][ERROR][com.github.mauricio.async.db.postgresql.PostgreSQLConnection:152] Error on connection
com.github.mauricio.async.db.postgresql.exceptions.GenericDatabaseException: ErrorMessage(fields=Map(Detail -> Key (user_phone)=(41661664466) already exists., s -> public, n -> basic_account_user_phone_idx, t -> basic_account, Line -> 535, File -> nbtinsert.c, SQLSTATE -> 23505, Routine -> _bt_check_unique, V -> ERROR, Message -> duplicate key value violates unique constraint "basic_account_user_phone_idx", Severity -> ERROR))
	at com.github.mauricio.async.db.postgresql.PostgreSQLConnection.onError(PostgreSQLConnection.scala:175) [postgresql-async_2.12-0.2.21.jar:0.2.21]
	at com.github.mauricio.async.db.postgresql.codec.PostgreSQLConnectionHandler.channelRead0(PostgreSQLConnectionHandler.scala:206) [postgresql-async_2.12-0.2.21.jar:0.2.21]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) [netty-codec-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [netty-codec-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426) [netty-codec-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) [netty-codec-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) [netty-common-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.30.Final.jar:4.1.30.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
[2019-07-05 19:36:32,739][vert.x-eventloop-thread-1][ERROR][com.github.mauricio.async.db.postgresql.PostgreSQLConnection:310] Setting error on future Future(<not completed>)
[2019-07-05 19:36:32,741][vert.x-eventloop-thread-0][INFO][com.rome.uaa.service.UaaServiceImpl:57] 2 exceptions occurred. 
[2019-07-05 19:37:26,065][vert.x-eventloop-thread-0][INFO][com.rome.uaa.MainVerticle:74] 初始化配置成功
[2019-07-05 19:37:29,606][vert.x-eventloop-thread-0][INFO][org.hibernate.validator.internal.util.Version:21] HV000001: Hibernate Validator 6.0.16.Final
[2019-07-05 19:37:39,099][vert.x-eventloop-thread-1][ERROR][com.github.mauricio.async.db.postgresql.PostgreSQLConnection:172] Error with message -> ErrorMessage(fields=Map(Detail -> Key (user_phone)=(4166166556) already exists., s -> public, n -> basic_account_user_phone_idx, t -> basic_account, Line -> 535, File -> nbtinsert.c, SQLSTATE -> 23505, Routine -> _bt_check_unique, V -> ERROR, Message -> duplicate key value violates unique constraint "basic_account_user_phone_idx", Severity -> ERROR))
[2019-07-05 19:37:39,099][vert.x-eventloop-thread-1][ERROR][com.github.mauricio.async.db.postgresql.PostgreSQLConnection:152] Error on connection
com.github.mauricio.async.db.postgresql.exceptions.GenericDatabaseException: ErrorMessage(fields=Map(Detail -> Key (user_phone)=(4166166556) already exists., s -> public, n -> basic_account_user_phone_idx, t -> basic_account, Line -> 535, File -> nbtinsert.c, SQLSTATE -> 23505, Routine -> _bt_check_unique, V -> ERROR, Message -> duplicate key value violates unique constraint "basic_account_user_phone_idx", Severity -> ERROR))
	at com.github.mauricio.async.db.postgresql.PostgreSQLConnection.onError(PostgreSQLConnection.scala:175) [postgresql-async_2.12-0.2.21.jar:0.2.21]
	at com.github.mauricio.async.db.postgresql.codec.PostgreSQLConnectionHandler.channelRead0(PostgreSQLConnectionHandler.scala:206) [postgresql-async_2.12-0.2.21.jar:0.2.21]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) [netty-codec-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [netty-codec-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426) [netty-codec-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) [netty-codec-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) [netty-common-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.30.Final.jar:4.1.30.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
[2019-07-05 19:37:39,103][vert.x-eventloop-thread-1][ERROR][com.github.mauricio.async.db.postgresql.PostgreSQLConnection:310] Setting error on future Future(<not completed>)
[2019-07-05 19:37:39,108][vert.x-eventloop-thread-0][INFO][com.rome.uaa.service.UaaServiceImpl:57] 2 exceptions occurred. 
[2019-07-05 19:38:26,950][vert.x-eventloop-thread-0][INFO][com.rome.uaa.service.UaaServiceImpl:77] null
[2019-07-05 19:38:47,877][vert.x-eventloop-thread-0][INFO][com.rome.uaa.service.UaaServiceImpl:77] 用户不存在
[2019-07-05 19:39:18,899][vert.x-eventloop-thread-0][INFO][com.rome.uaa.service.UaaServiceImpl:77] 用户不存在
[2019-07-05 19:39:32,534][vert.x-eventloop-thread-0][INFO][com.rome.uaa.service.UaaServiceImpl:77] 用户不存在
[2019-07-05 19:40:19,252][vert.x-eventloop-thread-0][INFO][com.rome.uaa.MainVerticle:74] 初始化配置成功
[2019-07-05 19:40:22,543][vert.x-eventloop-thread-0][INFO][org.hibernate.validator.internal.util.Version:21] HV000001: Hibernate Validator 6.0.16.Final
[2019-07-05 19:40:22,855][vert.x-eventloop-thread-0][INFO][com.rome.uaa.service.UaaServiceImpl:77] 用户不存在
[2019-07-05 19:41:19,316][vert.x-eventloop-thread-1][ERROR][com.github.mauricio.async.db.postgresql.PostgreSQLConnection:172] Error with message -> ErrorMessage(fields=Map(Detail -> Key (user_phone)=(4166166556) already exists., s -> public, n -> basic_account_user_phone_idx, t -> basic_account, Line -> 535, File -> nbtinsert.c, SQLSTATE -> 23505, Routine -> _bt_check_unique, V -> ERROR, Message -> duplicate key value violates unique constraint "basic_account_user_phone_idx", Severity -> ERROR))
[2019-07-05 19:41:19,317][vert.x-eventloop-thread-1][ERROR][com.github.mauricio.async.db.postgresql.PostgreSQLConnection:152] Error on connection
com.github.mauricio.async.db.postgresql.exceptions.GenericDatabaseException: ErrorMessage(fields=Map(Detail -> Key (user_phone)=(4166166556) already exists., s -> public, n -> basic_account_user_phone_idx, t -> basic_account, Line -> 535, File -> nbtinsert.c, SQLSTATE -> 23505, Routine -> _bt_check_unique, V -> ERROR, Message -> duplicate key value violates unique constraint "basic_account_user_phone_idx", Severity -> ERROR))
	at com.github.mauricio.async.db.postgresql.PostgreSQLConnection.onError(PostgreSQLConnection.scala:175) [postgresql-async_2.12-0.2.21.jar:0.2.21]
	at com.github.mauricio.async.db.postgresql.codec.PostgreSQLConnectionHandler.channelRead0(PostgreSQLConnectionHandler.scala:206) [postgresql-async_2.12-0.2.21.jar:0.2.21]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) [netty-codec-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [netty-codec-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426) [netty-codec-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) [netty-codec-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) [netty-common-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.30.Final.jar:4.1.30.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
[2019-07-05 19:41:19,321][vert.x-eventloop-thread-1][ERROR][com.github.mauricio.async.db.postgresql.PostgreSQLConnection:310] Setting error on future Future(<not completed>)
[2019-07-05 19:41:19,325][vert.x-eventloop-thread-0][INFO][com.rome.uaa.service.UaaServiceImpl:57] 2 exceptions occurred. 
[2019-07-05 19:42:59,593][vert.x-eventloop-thread-0][INFO][com.rome.uaa.service.UaaServiceImpl:77] null
[2019-07-05 19:46:14,483][vert.x-eventloop-thread-0][INFO][com.rome.uaa.service.UaaServiceImpl:77] 用户不存在
[2019-07-05 19:46:19,430][vert.x-eventloop-thread-0][INFO][com.rome.uaa.service.UaaServiceImpl:77] 用户不存在
[2019-07-05 19:46:23,304][vert.x-eventloop-thread-0][INFO][com.rome.uaa.service.UaaServiceImpl:77] 用户不存在
[2019-07-05 19:46:30,367][vert.x-eventloop-thread-0][INFO][com.rome.uaa.service.UaaServiceImpl:77] 用户不存在
[2019-07-06 10:53:10,167][vert.x-eventloop-thread-0][INFO][com.rome.uaa.MainVerticle:74] 初始化配置成功
[2019-07-06 11:10:35,943][vert.x-eventloop-thread-0][INFO][org.hibernate.validator.internal.util.Version:21] HV000001: Hibernate Validator 6.0.16.Final
[2019-07-06 11:25:39,997][vert.x-eventloop-thread-0][INFO][com.rome.uaa.service.UaaServiceImpl:83] null
[2019-07-06 11:28:07,341][vert.x-eventloop-thread-0][INFO][com.rome.uaa.MainVerticle:74] 初始化配置成功
[2019-07-06 11:28:12,228][vert.x-eventloop-thread-0][INFO][com.rome.uaa.service.UaaServiceImpl:83] null
[2019-07-06 11:30:01,813][vert.x-eventloop-thread-0][INFO][com.rome.uaa.MainVerticle:74] 初始化配置成功
[2019-07-06 11:33:20,796][vert.x-eventloop-thread-0][INFO][com.rome.uaa.MainVerticle:74] 初始化配置成功
[2019-07-06 11:37:09,773][vert.x-eventloop-thread-0][INFO][com.rome.uaa.MainVerticle:74] 初始化配置成功
[2019-07-06 11:44:23,927][vert.x-eventloop-thread-0][INFO][com.rome.uaa.MainVerticle:74] 初始化配置成功
[2019-07-06 11:44:32,403][vert.x-eventloop-thread-0][INFO][org.hibernate.validator.internal.util.Version:21] HV000001: Hibernate Validator 6.0.16.Final
[2019-07-06 11:46:50,607][vert.x-eventloop-thread-0][INFO][com.rome.uaa.MainVerticle:74] 初始化配置成功
[2019-07-06 11:46:55,767][vert.x-eventloop-thread-0][INFO][org.hibernate.validator.internal.util.Version:21] HV000001: Hibernate Validator 6.0.16.Final
[2019-07-06 11:47:18,269][vert.x-eventloop-thread-0][INFO][com.rome.uaa.MainVerticle:74] 初始化配置成功
[2019-07-06 11:47:25,209][vert.x-eventloop-thread-0][INFO][org.hibernate.validator.internal.util.Version:21] HV000001: Hibernate Validator 6.0.16.Final
[2019-07-06 11:57:27,007][vert.x-eventloop-thread-0][INFO][com.rome.uaa.MainVerticle:74] 初始化配置成功
[2019-07-06 11:57:33,068][vert.x-eventloop-thread-0][INFO][org.hibernate.validator.internal.util.Version:21] HV000001: Hibernate Validator 6.0.16.Final
[2019-07-06 11:58:24,611][vert.x-eventloop-thread-0][INFO][com.rome.uaa.MainVerticle:74] 初始化配置成功
[2019-07-06 11:58:28,770][vert.x-eventloop-thread-0][INFO][org.hibernate.validator.internal.util.Version:21] HV000001: Hibernate Validator 6.0.16.Final
[2019-07-06 12:00:21,172][vert.x-eventloop-thread-0][INFO][com.rome.uaa.MainVerticle:74] 初始化配置成功
[2019-07-06 12:00:55,494][vert.x-eventloop-thread-0][INFO][org.hibernate.validator.internal.util.Version:21] HV000001: Hibernate Validator 6.0.16.Final
[2019-07-06 13:10:48,058][vert.x-eventloop-thread-0][INFO][com.rome.uaa.MainVerticle:74] 初始化配置成功
[2019-07-06 13:10:53,948][vert.x-eventloop-thread-0][INFO][org.hibernate.validator.internal.util.Version:21] HV000001: Hibernate Validator 6.0.16.Final
[2019-07-06 13:18:31,164][vert.x-eventloop-thread-0][INFO][com.rome.uaa.MainVerticle:74] 初始化配置成功
[2019-07-06 13:18:34,597][vert.x-eventloop-thread-0][INFO][org.hibernate.validator.internal.util.Version:21] HV000001: Hibernate Validator 6.0.16.Final
[2019-07-06 13:18:35,094][vert.x-eventloop-thread-1][ERROR][com.github.mauricio.async.db.postgresql.PostgreSQLConnection:172] Error with message -> ErrorMessage(fields=Map(Detail -> Key (user_phone)=(45751116556) already exists., s -> public, n -> basic_account_user_phone_idx, t -> basic_account, Line -> 535, File -> nbtinsert.c, SQLSTATE -> 23505, Routine -> _bt_check_unique, V -> ERROR, Message -> duplicate key value violates unique constraint "basic_account_user_phone_idx", Severity -> ERROR))
[2019-07-06 13:18:35,095][vert.x-eventloop-thread-1][ERROR][com.github.mauricio.async.db.postgresql.PostgreSQLConnection:152] Error on connection
com.github.mauricio.async.db.postgresql.exceptions.GenericDatabaseException: ErrorMessage(fields=Map(Detail -> Key (user_phone)=(45751116556) already exists., s -> public, n -> basic_account_user_phone_idx, t -> basic_account, Line -> 535, File -> nbtinsert.c, SQLSTATE -> 23505, Routine -> _bt_check_unique, V -> ERROR, Message -> duplicate key value violates unique constraint "basic_account_user_phone_idx", Severity -> ERROR))
	at com.github.mauricio.async.db.postgresql.PostgreSQLConnection.onError(PostgreSQLConnection.scala:175) [postgresql-async_2.12-0.2.21.jar:0.2.21]
	at com.github.mauricio.async.db.postgresql.codec.PostgreSQLConnectionHandler.channelRead0(PostgreSQLConnectionHandler.scala:206) [postgresql-async_2.12-0.2.21.jar:0.2.21]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) [netty-codec-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [netty-codec-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426) [netty-codec-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) [netty-codec-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) [netty-common-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.30.Final.jar:4.1.30.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
[2019-07-06 13:18:35,100][vert.x-eventloop-thread-1][ERROR][com.github.mauricio.async.db.postgresql.PostgreSQLConnection:310] Setting error on future Future(<not completed>)
[2019-07-06 13:18:35,106][vert.x-eventloop-thread-0][INFO][com.rome.uaa.service.UaaServiceImpl:59] 2 exceptions occurred. 
[2019-07-06 13:18:44,601][vert.x-eventloop-thread-1][ERROR][com.github.mauricio.async.db.postgresql.PostgreSQLConnection:172] Error with message -> ErrorMessage(fields=Map(Detail -> Key (user_phone)=(45751116556) already exists., s -> public, n -> basic_account_user_phone_idx, t -> basic_account, Line -> 535, File -> nbtinsert.c, SQLSTATE -> 23505, Routine -> _bt_check_unique, V -> ERROR, Message -> duplicate key value violates unique constraint "basic_account_user_phone_idx", Severity -> ERROR))
[2019-07-06 13:18:44,602][vert.x-eventloop-thread-1][ERROR][com.github.mauricio.async.db.postgresql.PostgreSQLConnection:152] Error on connection
com.github.mauricio.async.db.postgresql.exceptions.GenericDatabaseException: ErrorMessage(fields=Map(Detail -> Key (user_phone)=(45751116556) already exists., s -> public, n -> basic_account_user_phone_idx, t -> basic_account, Line -> 535, File -> nbtinsert.c, SQLSTATE -> 23505, Routine -> _bt_check_unique, V -> ERROR, Message -> duplicate key value violates unique constraint "basic_account_user_phone_idx", Severity -> ERROR))
	at com.github.mauricio.async.db.postgresql.PostgreSQLConnection.onError(PostgreSQLConnection.scala:175) [postgresql-async_2.12-0.2.21.jar:0.2.21]
	at com.github.mauricio.async.db.postgresql.codec.PostgreSQLConnectionHandler.channelRead0(PostgreSQLConnectionHandler.scala:206) [postgresql-async_2.12-0.2.21.jar:0.2.21]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) [netty-codec-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [netty-codec-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426) [netty-codec-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) [netty-codec-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) [netty-common-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.30.Final.jar:4.1.30.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
[2019-07-06 13:18:44,602][vert.x-eventloop-thread-1][ERROR][com.github.mauricio.async.db.postgresql.PostgreSQLConnection:310] Setting error on future Future(<not completed>)
[2019-07-06 13:18:44,606][vert.x-eventloop-thread-0][INFO][com.rome.uaa.service.UaaServiceImpl:59] 2 exceptions occurred. 
[2019-07-06 13:21:47,773][vert.x-eventloop-thread-0][INFO][com.rome.uaa.MainVerticle:74] 初始化配置成功
[2019-07-06 13:24:13,798][vert.x-eventloop-thread-0][INFO][com.rome.uaa.MainVerticle:74] 初始化配置成功
[2019-07-06 13:24:34,052][vert.x-eventloop-thread-0][INFO][org.hibernate.validator.internal.util.Version:21] HV000001: Hibernate Validator 6.0.16.Final
[2019-07-06 13:28:31,645][vert.x-eventloop-thread-0][INFO][com.rome.uaa.service.UaaServiceImpl:85] null
[2019-07-06 13:29:07,382][vert.x-eventloop-thread-0][INFO][com.rome.uaa.MainVerticle:74] 初始化配置成功
[2019-07-06 13:29:15,432][vert.x-eventloop-thread-0][INFO][com.rome.uaa.service.UaaServiceImpl:85] null
[2019-07-06 13:29:20,510][vert.x-eventloop-thread-0][INFO][com.rome.uaa.service.UaaServiceImpl:85] null
[2019-07-06 13:32:07,769][vert.x-eventloop-thread-0][INFO][com.rome.uaa.service.UaaServiceImpl:85] null
[2019-07-06 13:32:47,193][vert.x-eventloop-thread-0][INFO][com.rome.uaa.MainVerticle:74] 初始化配置成功
[2019-07-06 13:33:01,661][vert.x-eventloop-thread-0][INFO][com.rome.uaa.service.UaaServiceImpl:85] null
[2019-07-06 13:34:12,208][vert.x-eventloop-thread-0][INFO][org.hibernate.validator.internal.util.Version:21] HV000001: Hibernate Validator 6.0.16.Final
[2019-07-06 13:34:12,641][vert.x-eventloop-thread-0][INFO][com.rome.uaa.service.UaaServiceImpl:79] 密码错误
[2019-07-06 14:58:03,054][vert.x-eventloop-thread-0][INFO][com.rome.uaa.MainVerticle:74] 初始化配置成功
[2019-07-06 15:04:44,146][vert.x-eventloop-thread-0][INFO][com.rome.uaa.MainVerticle:76] 初始化配置成功
[2019-07-06 15:06:59,288][vert.x-eventloop-thread-0][INFO][com.rome.uaa.MainVerticle:76] 初始化配置成功
[2019-07-06 15:07:27,884][vert.x-eventloop-thread-0][INFO][com.rome.uaa.MainVerticle:76] 初始化配置成功
[2019-07-06 15:08:15,196][vert.x-eventloop-thread-0][INFO][com.rome.uaa.MainVerticle:76] 初始化配置成功
[2019-07-06 15:09:16,496][vert.x-eventloop-thread-0][INFO][com.rome.uaa.MainVerticle:76] 初始化配置成功
[2019-07-06 15:10:17,837][vert.x-eventloop-thread-0][INFO][org.hibernate.validator.internal.util.Version:21] HV000001: Hibernate Validator 6.0.16.Final
[2019-07-06 15:12:58,997][vert.x-eventloop-thread-0][INFO][com.rome.uaa.MainVerticle:76] 初始化配置成功
[2019-07-06 15:13:02,457][vert.x-eventloop-thread-0][INFO][org.hibernate.validator.internal.util.Version:21] HV000001: Hibernate Validator 6.0.16.Final
